# Generated by Django 5.1.4 on 2026-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0014_product_correction_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsourcerow',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productsourcerejectedrow',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='externaldatacorrectionmemory',
            name='record_key',
            field=models.CharField(blank=True, db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='productcorrectiondecision',
            name='sku',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productreconciliationdecision',
            name='product_code_normalized',
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AddIndex(
            model_name='productsourcerow',
            index=models.Index(fields=['external_file', 'customer_code', 'product_code_normalized'], name='imp_prod_file_cust_sku_idx'),
        ),
    ]
