# Generated by Django 5.1.4 on 2026-06-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address_line_1', models.CharField(blank=True, max_length=180)),
                ('address_line_2', models.CharField(blank=True, max_length=180)),
                ('suburb', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(default='Australia', max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_addresses', to='clients.client')),
            ],
            options={
                'ordering': ['client__code', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('normalized_key', models.CharField(db_index=True, max_length=180)),
            ],
            options={
                'ordering': ['state', 'suburb_name', 'postcode'],
                'indexes': [models.Index(fields=['suburb_name', 'state'], name='locations_s_suburb__b8876b_idx'), models.Index(fields=['state', 'postcode'], name='locations_s_state_d9cf1b_idx')],
                'unique_together': {('suburb_name', 'state', 'postcode')},
            },
        ),
    ]
