# Generated by Django 5.1.4 on 2026-06-04 09:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierTailgateCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('per_subsequent_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('hand_unload_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailgate_charges', to='clients.client')),
            ],
            options={
                'unique_together': {('client', 'carrier')},
            },
        ),
        migrations.CreateModel(
            name='FreightRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=40)),
                ('subzone', models.CharField(blank=True, max_length=40)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('weight_break', models.CharField(blank=True, max_length=40)),
                ('freight_type', models.CharField(blank=True, max_length=5)),
                ('customer_code', models.CharField(default='STH', max_length=30)),
                ('minimum_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('basic_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('per_subsequent_basic', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('per_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('overweight_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('remote_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('offshore_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('overlength_charge', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('margin', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('lookup_key', models.CharField(blank=True, db_index=True, max_length=260)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('carrier_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrierservice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'lookup_key'], name='rates_freig_client__a858ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='FreightZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('zone', models.CharField(blank=True, max_length=40)),
                ('subzone', models.CharField(blank=True, max_length=40)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('lookup_key_suburb', models.CharField(blank=True, db_index=True, max_length=220)),
                ('lookup_key_postcode', models.CharField(blank=True, db_index=True, max_length=220)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('carrier_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrierservice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'suburb', 'state'], name='rates_freig_client__a9de05_idx'), models.Index(fields=['client', 'postcode'], name='rates_freig_client__59464e_idx')],
            },
        ),
    ]
