--
-- PostgreSQL database dump
--

\restrict 65vDab7vxIXxzkBvEifQktDd9Z5mgQBtBFyF0INp3ZlDkOntakOVQPNYF16uVUE

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: audit_auditevent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_auditevent (
    id bigint NOT NULL,
    event_type character varying(80) NOT NULL,
    message text NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    actor_id integer,
    client_id bigint,
    external_file_id bigint,
    severity character varying(12) NOT NULL,
    ip_address inet,
    request_id character varying(64) NOT NULL
);


--
-- Name: audit_auditevent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_auditevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_auditevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_gateway_calculatoruserprofile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authentication_gateway_calculatoruserprofile (
    id bigint NOT NULL,
    role character varying(30) NOT NULL,
    client_scope character varying(30) NOT NULL,
    calculator_access boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint,
    user_id integer NOT NULL,
    CONSTRAINT authgw_profile_role_scope_client_valid CHECK ((((client_id IS NOT NULL) AND ((client_scope)::text = 'SINGLE_CLIENT'::text) AND ((role)::text = 'CUSTOMER_USER'::text)) OR ((client_id IS NULL) AND ((client_scope)::text = ANY (ARRAY[('ALL_CLIENTS'::character varying)::text, ('SELECTED_CLIENTS'::character varying)::text])) AND ((role)::text = 'INTERNAL_USER'::text))))
);


--
-- Name: authentication_gateway_calculatoruserprofile_allowed_clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authentication_gateway_calculatoruserprofile_allowed_clients (
    id bigint NOT NULL,
    calculatoruserprofile_id bigint NOT NULL,
    client_id bigint NOT NULL
);


--
-- Name: authentication_gateway_calculatoruserprofile_allowed_cli_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authentication_gateway_calculatoruserprofile_allowed_clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_gateway_calculatoruserprofile_allowed_cli_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_gateway_calculatoruserprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authentication_gateway_calculatoruserprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_gateway_calculatoruserprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carriers_carrier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carriers_carrier (
    id bigint NOT NULL,
    code character varying(40) NOT NULL,
    name character varying(150) NOT NULL,
    active boolean NOT NULL
);


--
-- Name: carriers_carrier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carriers_carrier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carriers_carrier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carriers_carrierservice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carriers_carrierservice (
    id bigint NOT NULL,
    service_code character varying(40) NOT NULL,
    service_name character varying(150) NOT NULL,
    active boolean NOT NULL,
    carrier_id bigint NOT NULL
);


--
-- Name: carriers_carrierservice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carriers_carrierservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carriers_carrierservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carriers_clientcarrierconfig; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carriers_clientcarrierconfig (
    id bigint NOT NULL,
    customer_code character varying(30) NOT NULL,
    ratecard character varying(80) NOT NULL,
    fuel_levy numeric(10,6) NOT NULL,
    extra_surcharge numeric(10,6) NOT NULL,
    uprate numeric(10,6) NOT NULL,
    cubic_conversion numeric(10,3) NOT NULL,
    tailgate_enabled boolean NOT NULL,
    hand_unload_enabled boolean NOT NULL,
    subzone_enabled boolean NOT NULL,
    area_enabled boolean NOT NULL,
    overlength_enabled boolean NOT NULL,
    pallet_enabled boolean NOT NULL,
    carton_enabled boolean NOT NULL,
    active boolean NOT NULL,
    carrier_service_id bigint NOT NULL,
    client_id bigint NOT NULL,
    warehouse_handling_enabled boolean NOT NULL,
    fixed_handling_charge numeric(12,4) NOT NULL,
    zone_enabled boolean NOT NULL,
    postcode_zones_enabled boolean NOT NULL,
    empty_rate_enabled boolean NOT NULL,
    base_status character varying(5) NOT NULL,
    order_ready_rule character varying(40) NOT NULL,
    fuel_levy_source character varying(30) NOT NULL,
    fuel_levy_updated_at timestamp with time zone,
    fuel_data_file_id bigint
);


--
-- Name: carriers_clientcarrierconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carriers_clientcarrierconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carriers_clientcarrierconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients_client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients_client (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(150) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: clients_client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clients_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients_freightcalculator; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients_freightcalculator (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    version character varying(80) NOT NULL,
    calculation_engine_key character varying(80) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL
);


--
-- Name: clients_freightcalculator_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clients_freightcalculator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_freightcalculator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: imports_externaldatafile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.imports_externaldatafile (
    id bigint NOT NULL,
    file_type character varying(30) NOT NULL,
    original_filename character varying(255) NOT NULL,
    stored_path character varying(500) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    status character varying(30) NOT NULL,
    last_imported_at timestamp with time zone,
    import_summary jsonb NOT NULL,
    error_message text NOT NULL,
    client_id bigint NOT NULL,
    uploaded_by_id integer,
    source_method character varying(30) NOT NULL,
    source_url character varying(1000) NOT NULL,
    uploaded_file character varying(100),
    file_size_bytes bigint NOT NULL,
    mime_type character varying(120) NOT NULL,
    sha256 character varying(64) NOT NULL,
    notes text NOT NULL,
    validation_summary jsonb NOT NULL,
    validated_at timestamp with time zone,
    validated_by_id integer,
    imported_by_id integer,
    activated_at timestamp with time zone,
    activated_by_id integer,
    rolled_back_at timestamp with time zone,
    rolled_back_by_id integer,
    previous_active_file_id bigint,
    CONSTRAINT imports_externaldatafile_file_size_bytes_check CHECK ((file_size_bytes >= 0))
);


--
-- Name: imports_externaldatafile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.imports_externaldatafile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imports_externaldatafile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imports_productsourcerow; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.imports_productsourcerow (
    id bigint NOT NULL,
    source_row_number integer NOT NULL,
    product_code_raw character varying(255) NOT NULL,
    product_code_normalized character varying(255) NOT NULL,
    name character varying(500) NOT NULL,
    description text NOT NULL,
    category character varying(255) NOT NULL,
    length_mm numeric(20,6),
    width_mm numeric(20,6),
    height_mm numeric(20,6),
    cubic_m3 numeric(20,6),
    quantity numeric(20,6),
    weight_kg numeric(20,6),
    pallet numeric(20,6),
    comment text NOT NULL,
    source_status character varying(100) NOT NULL,
    raw_data jsonb NOT NULL,
    validation_errors jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    external_file_id bigint NOT NULL,
    CONSTRAINT imports_productsourcerow_source_row_number_check CHECK ((source_row_number >= 0))
);


--
-- Name: imports_productsourcerow_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.imports_productsourcerow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imports_productsourcerow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imports_stocksourcerow; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.imports_stocksourcerow (
    id bigint NOT NULL,
    source_row_number integer NOT NULL,
    movement_number character varying(100) NOT NULL,
    stock_date_raw character varying(100) NOT NULL,
    customer character varying(100) NOT NULL,
    product_code_raw character varying(255) NOT NULL,
    product_code_normalized character varying(255) NOT NULL,
    sql_name character varying(500) NOT NULL,
    quantity numeric(20,6),
    pallet numeric(20,6),
    group1 character varying(255) NOT NULL,
    location character varying(255) NOT NULL,
    stock_class character varying(255) NOT NULL,
    sql_stock_ref character varying(255) NOT NULL,
    weight_kg numeric(20,6),
    cubic_m3 numeric(20,6),
    depot character varying(255) NOT NULL,
    sql_group character varying(255) NOT NULL,
    sql_group1 character varying(255) NOT NULL,
    expiry_raw character varying(100) NOT NULL,
    pallet_ref character varying(255) NOT NULL,
    serial_no character varying(255) NOT NULL,
    source_status character varying(100) NOT NULL,
    raw_data jsonb NOT NULL,
    validation_errors jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    external_file_id bigint NOT NULL,
    CONSTRAINT imports_stocksourcerow_source_row_number_check CHECK ((source_row_number >= 0))
);


--
-- Name: imports_stocksourcerow_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.imports_stocksourcerow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imports_stocksourcerow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations_fromaddress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations_fromaddress (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    address_line_1 character varying(180) NOT NULL,
    address_line_2 character varying(180) NOT NULL,
    suburb character varying(120) NOT NULL,
    state character varying(10) NOT NULL,
    postcode character varying(10) NOT NULL,
    country character varying(80) NOT NULL,
    is_default boolean NOT NULL,
    active boolean NOT NULL,
    client_id bigint NOT NULL
);


--
-- Name: locations_fromaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.locations_fromaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_fromaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations_suburb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations_suburb (
    id bigint NOT NULL,
    suburb_name character varying(120) NOT NULL,
    state character varying(10) NOT NULL,
    postcode character varying(10) NOT NULL,
    normalized_key character varying(180) NOT NULL
);


--
-- Name: locations_suburb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.locations_suburb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_suburb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    sku character varying(80) NOT NULL,
    name character varying(240) NOT NULL,
    description text NOT NULL,
    length_m numeric(12,4) NOT NULL,
    width_m numeric(12,4) NOT NULL,
    height_m numeric(12,4) NOT NULL,
    weight_kg numeric(12,4) NOT NULL,
    cubic_m3 numeric(12,6) NOT NULL,
    freight_type character varying(1) NOT NULL,
    active boolean NOT NULL,
    source_row integer,
    client_id bigint NOT NULL,
    CONSTRAINT products_product_source_row_check CHECK ((source_row >= 0))
);


--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productkitcomponent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_productkitcomponent (
    id bigint NOT NULL,
    parent_sku character varying(80) NOT NULL,
    component_sku character varying(80) NOT NULL,
    quantity numeric(12,4) NOT NULL,
    client_id bigint NOT NULL
);


--
-- Name: products_productkitcomponent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_productkitcomponent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productkitcomponent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rates_carriertailgatecharge; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rates_carriertailgatecharge (
    id bigint NOT NULL,
    minimum_charge numeric(12,4) NOT NULL,
    per_subsequent_charge numeric(12,4) NOT NULL,
    hand_unload_charge numeric(12,4) NOT NULL,
    carrier_id bigint NOT NULL,
    client_id bigint NOT NULL
);


--
-- Name: rates_carriertailgatecharge_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rates_carriertailgatecharge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rates_carriertailgatecharge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rates_freightrate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rates_freightrate (
    id bigint NOT NULL,
    zone character varying(40) NOT NULL,
    subzone character varying(40) NOT NULL,
    area character varying(80) NOT NULL,
    weight_break character varying(40) NOT NULL,
    freight_type character varying(5) NOT NULL,
    customer_code character varying(30) NOT NULL,
    minimum_charge numeric(14,6) NOT NULL,
    basic_charge numeric(14,6) NOT NULL,
    per_subsequent_basic numeric(14,6) NOT NULL,
    per_kg numeric(14,6) NOT NULL,
    overweight_charge numeric(14,6) NOT NULL,
    remote_charge numeric(14,6) NOT NULL,
    offshore_charge numeric(14,6) NOT NULL,
    overlength_charge numeric(14,6) NOT NULL,
    margin numeric(10,6) NOT NULL,
    lookup_key character varying(260) NOT NULL,
    source_row integer,
    carrier_service_id bigint NOT NULL,
    client_id bigint NOT NULL,
    CONSTRAINT rates_freightrate_source_row_check CHECK ((source_row >= 0))
);


--
-- Name: rates_freightrate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rates_freightrate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rates_freightrate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rates_freightzone; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rates_freightzone (
    id bigint NOT NULL,
    suburb character varying(120) NOT NULL,
    state character varying(10) NOT NULL,
    postcode character varying(10) NOT NULL,
    zone character varying(40) NOT NULL,
    subzone character varying(40) NOT NULL,
    area character varying(80) NOT NULL,
    lookup_key_suburb character varying(220) NOT NULL,
    lookup_key_postcode character varying(220) NOT NULL,
    source_row integer,
    carrier_service_id bigint NOT NULL,
    client_id bigint NOT NULL,
    CONSTRAINT rates_freightzone_source_row_check CHECK ((source_row >= 0))
);


--
-- Name: rates_freightzone_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rates_freightzone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rates_freightzone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_estimates_savedestimate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_estimates_savedestimate (
    id bigint NOT NULL,
    reference character varying(64) NOT NULL,
    created_by_label character varying(254) NOT NULL,
    schema_version smallint NOT NULL,
    input_snapshot jsonb NOT NULL,
    result_snapshot jsonb NOT NULL,
    destination_label character varying(220) NOT NULL,
    total_weight_kg numeric(14,3),
    total_cubic_m3 numeric(14,3),
    best_estimate_ex_gst numeric(14,2),
    selected_option_index integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id integer,
    CONSTRAINT saved_estimates_savedestimate_schema_version_check CHECK ((schema_version >= 0)),
    CONSTRAINT saved_estimates_savedestimate_selected_option_index_check CHECK ((selected_option_index >= 0))
);


--
-- Name: saved_estimates_savedestimate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saved_estimates_savedestimate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_estimates_savedestimate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_auditevent audit_auditevent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_auditevent
    ADD CONSTRAINT audit_auditevent_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authentication_gateway_calculatoruserprofile_allowed_clients authentication_gateway_c_calculatoruserprofile_id_c4066cf2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile_allowed_clients
    ADD CONSTRAINT authentication_gateway_c_calculatoruserprofile_id_c4066cf2_uniq UNIQUE (calculatoruserprofile_id, client_id);


--
-- Name: authentication_gateway_calculatoruserprofile_allowed_clients authentication_gateway_calculatoruserprofile_allowed_clien_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile_allowed_clients
    ADD CONSTRAINT authentication_gateway_calculatoruserprofile_allowed_clien_pkey PRIMARY KEY (id);


--
-- Name: authentication_gateway_calculatoruserprofile authentication_gateway_calculatoruserprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile
    ADD CONSTRAINT authentication_gateway_calculatoruserprofile_pkey PRIMARY KEY (id);


--
-- Name: authentication_gateway_calculatoruserprofile authentication_gateway_calculatoruserprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile
    ADD CONSTRAINT authentication_gateway_calculatoruserprofile_user_id_key UNIQUE (user_id);


--
-- Name: carriers_carrier carriers_carrier_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_carrier
    ADD CONSTRAINT carriers_carrier_code_key UNIQUE (code);


--
-- Name: carriers_carrier carriers_carrier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_carrier
    ADD CONSTRAINT carriers_carrier_pkey PRIMARY KEY (id);


--
-- Name: carriers_carrierservice carriers_carrierservice_carrier_id_service_code_aaf1e5b8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_carrierservice
    ADD CONSTRAINT carriers_carrierservice_carrier_id_service_code_aaf1e5b8_uniq UNIQUE (carrier_id, service_code);


--
-- Name: carriers_carrierservice carriers_carrierservice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_carrierservice
    ADD CONSTRAINT carriers_carrierservice_pkey PRIMARY KEY (id);


--
-- Name: carriers_clientcarrierconfig carriers_clientcarrierco_client_id_carrier_servic_69ba9f2c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_clientcarrierconfig
    ADD CONSTRAINT carriers_clientcarrierco_client_id_carrier_servic_69ba9f2c_uniq UNIQUE (client_id, carrier_service_id);


--
-- Name: carriers_clientcarrierconfig carriers_clientcarrierconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_clientcarrierconfig
    ADD CONSTRAINT carriers_clientcarrierconfig_pkey PRIMARY KEY (id);


--
-- Name: clients_client clients_client_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients_client
    ADD CONSTRAINT clients_client_code_key UNIQUE (code);


--
-- Name: clients_client clients_client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients_client
    ADD CONSTRAINT clients_client_pkey PRIMARY KEY (id);


--
-- Name: clients_freightcalculator clients_freightcalculator_client_id_name_version_b78b1510_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients_freightcalculator
    ADD CONSTRAINT clients_freightcalculator_client_id_name_version_b78b1510_uniq UNIQUE (client_id, name, version);


--
-- Name: clients_freightcalculator clients_freightcalculator_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients_freightcalculator
    ADD CONSTRAINT clients_freightcalculator_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: imports_externaldatafile imports_externaldatafile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldatafile_pkey PRIMARY KEY (id);


--
-- Name: imports_productsourcerow imports_product_source_file_row_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_productsourcerow
    ADD CONSTRAINT imports_product_source_file_row_uniq UNIQUE (external_file_id, source_row_number);


--
-- Name: imports_productsourcerow imports_productsourcerow_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_productsourcerow
    ADD CONSTRAINT imports_productsourcerow_pkey PRIMARY KEY (id);


--
-- Name: imports_stocksourcerow imports_stock_source_file_row_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_stocksourcerow
    ADD CONSTRAINT imports_stock_source_file_row_uniq UNIQUE (external_file_id, source_row_number);


--
-- Name: imports_stocksourcerow imports_stocksourcerow_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_stocksourcerow
    ADD CONSTRAINT imports_stocksourcerow_pkey PRIMARY KEY (id);


--
-- Name: locations_fromaddress locations_fromaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations_fromaddress
    ADD CONSTRAINT locations_fromaddress_pkey PRIMARY KEY (id);


--
-- Name: locations_suburb locations_suburb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations_suburb
    ADD CONSTRAINT locations_suburb_pkey PRIMARY KEY (id);


--
-- Name: locations_suburb locations_suburb_suburb_name_state_postcode_e36db4c3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations_suburb
    ADD CONSTRAINT locations_suburb_suburb_name_state_postcode_e36db4c3_uniq UNIQUE (suburb_name, state, postcode);


--
-- Name: products_product products_product_client_id_sku_d3c551e6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_client_id_sku_d3c551e6_uniq UNIQUE (client_id, sku);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_productkitcomponent products_productkitcompo_client_id_parent_sku_com_8ceffe4d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_productkitcomponent
    ADD CONSTRAINT products_productkitcompo_client_id_parent_sku_com_8ceffe4d_uniq UNIQUE (client_id, parent_sku, component_sku);


--
-- Name: products_productkitcomponent products_productkitcomponent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_productkitcomponent
    ADD CONSTRAINT products_productkitcomponent_pkey PRIMARY KEY (id);


--
-- Name: rates_carriertailgatecharge rates_carriertailgatecharge_client_id_carrier_id_740e68a6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_carriertailgatecharge
    ADD CONSTRAINT rates_carriertailgatecharge_client_id_carrier_id_740e68a6_uniq UNIQUE (client_id, carrier_id);


--
-- Name: rates_carriertailgatecharge rates_carriertailgatecharge_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_carriertailgatecharge
    ADD CONSTRAINT rates_carriertailgatecharge_pkey PRIMARY KEY (id);


--
-- Name: rates_freightrate rates_freightrate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_freightrate
    ADD CONSTRAINT rates_freightrate_pkey PRIMARY KEY (id);


--
-- Name: rates_freightzone rates_freightzone_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_freightzone
    ADD CONSTRAINT rates_freightzone_pkey PRIMARY KEY (id);


--
-- Name: saved_estimates_savedestimate saved_estimates_savedestimate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_estimates_savedestimate
    ADD CONSTRAINT saved_estimates_savedestimate_pkey PRIMARY KEY (id);


--
-- Name: saved_estimates_savedestimate saved_estimates_savedestimate_reference_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_estimates_savedestimate
    ADD CONSTRAINT saved_estimates_savedestimate_reference_key UNIQUE (reference);


--
-- Name: audit_auditevent_actor_id_270bb4b7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_actor_id_270bb4b7 ON public.audit_auditevent USING btree (actor_id);


--
-- Name: audit_auditevent_client_id_b7cf9ec4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_client_id_b7cf9ec4 ON public.audit_auditevent USING btree (client_id);


--
-- Name: audit_auditevent_created_at_58e81936; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_created_at_58e81936 ON public.audit_auditevent USING btree (created_at);


--
-- Name: audit_auditevent_event_type_f13571f1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_event_type_f13571f1 ON public.audit_auditevent USING btree (event_type);


--
-- Name: audit_auditevent_event_type_f13571f1_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_event_type_f13571f1_like ON public.audit_auditevent USING btree (event_type varchar_pattern_ops);


--
-- Name: audit_auditevent_external_file_id_0ef52357; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_external_file_id_0ef52357 ON public.audit_auditevent USING btree (external_file_id);


--
-- Name: audit_auditevent_request_id_b6fdcfa6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_request_id_b6fdcfa6 ON public.audit_auditevent USING btree (request_id);


--
-- Name: audit_auditevent_request_id_b6fdcfa6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_request_id_b6fdcfa6_like ON public.audit_auditevent USING btree (request_id varchar_pattern_ops);


--
-- Name: audit_auditevent_severity_89be939a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_severity_89be939a ON public.audit_auditevent USING btree (severity);


--
-- Name: audit_auditevent_severity_89be939a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_auditevent_severity_89be939a_like ON public.audit_auditevent USING btree (severity varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authentication_gateway_cal_calculatoruserprofile_id_94d347db; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_gateway_cal_calculatoruserprofile_id_94d347db ON public.authentication_gateway_calculatoruserprofile_allowed_clients USING btree (calculatoruserprofile_id);


--
-- Name: authentication_gateway_cal_client_id_1210bcb2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_gateway_cal_client_id_1210bcb2 ON public.authentication_gateway_calculatoruserprofile_allowed_clients USING btree (client_id);


--
-- Name: authentication_gateway_calculatoruserprofile_client_id_c76711e3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_gateway_calculatoruserprofile_client_id_c76711e3 ON public.authentication_gateway_calculatoruserprofile USING btree (client_id);


--
-- Name: carriers_carrier_code_d3857c9e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX carriers_carrier_code_d3857c9e_like ON public.carriers_carrier USING btree (code varchar_pattern_ops);


--
-- Name: carriers_carrierservice_carrier_id_4b678580; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX carriers_carrierservice_carrier_id_4b678580 ON public.carriers_carrierservice USING btree (carrier_id);


--
-- Name: carriers_clientcarrierconfig_carrier_service_id_5f7bde01; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX carriers_clientcarrierconfig_carrier_service_id_5f7bde01 ON public.carriers_clientcarrierconfig USING btree (carrier_service_id);


--
-- Name: carriers_clientcarrierconfig_client_id_4355b5f2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX carriers_clientcarrierconfig_client_id_4355b5f2 ON public.carriers_clientcarrierconfig USING btree (client_id);


--
-- Name: carriers_clientcarrierconfig_fuel_data_file_id_a037f4b0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX carriers_clientcarrierconfig_fuel_data_file_id_a037f4b0 ON public.carriers_clientcarrierconfig USING btree (fuel_data_file_id);


--
-- Name: clients_client_code_02517314_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clients_client_code_02517314_like ON public.clients_client USING btree (code varchar_pattern_ops);


--
-- Name: clients_freightcalculator_client_id_36cb7f7e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clients_freightcalculator_client_id_36cb7f7e ON public.clients_freightcalculator USING btree (client_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: imp_prod_file_sku_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imp_prod_file_sku_idx ON public.imports_productsourcerow USING btree (external_file_id, product_code_normalized);


--
-- Name: imp_stock_file_sku_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imp_stock_file_sku_idx ON public.imports_stocksourcerow USING btree (external_file_id, product_code_normalized);


--
-- Name: imports_externaldatafile_activated_by_id_6efc2ba2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_activated_by_id_6efc2ba2 ON public.imports_externaldatafile USING btree (activated_by_id);


--
-- Name: imports_externaldatafile_client_id_ec2c0529; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_client_id_ec2c0529 ON public.imports_externaldatafile USING btree (client_id);


--
-- Name: imports_externaldatafile_imported_by_id_d75cf480; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_imported_by_id_d75cf480 ON public.imports_externaldatafile USING btree (imported_by_id);


--
-- Name: imports_externaldatafile_previous_active_file_id_a8159ee8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_previous_active_file_id_a8159ee8 ON public.imports_externaldatafile USING btree (previous_active_file_id);


--
-- Name: imports_externaldatafile_rolled_back_by_id_af5c253f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_rolled_back_by_id_af5c253f ON public.imports_externaldatafile USING btree (rolled_back_by_id);


--
-- Name: imports_externaldatafile_sha256_0b047ab1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_sha256_0b047ab1 ON public.imports_externaldatafile USING btree (sha256);


--
-- Name: imports_externaldatafile_sha256_0b047ab1_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_sha256_0b047ab1_like ON public.imports_externaldatafile USING btree (sha256 varchar_pattern_ops);


--
-- Name: imports_externaldatafile_status_133934e0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_status_133934e0 ON public.imports_externaldatafile USING btree (status);


--
-- Name: imports_externaldatafile_status_133934e0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_status_133934e0_like ON public.imports_externaldatafile USING btree (status varchar_pattern_ops);


--
-- Name: imports_externaldatafile_uploaded_by_id_d42115b5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_uploaded_by_id_d42115b5 ON public.imports_externaldatafile USING btree (uploaded_by_id);


--
-- Name: imports_externaldatafile_validated_by_id_8f30fe70; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_externaldatafile_validated_by_id_8f30fe70 ON public.imports_externaldatafile USING btree (validated_by_id);


--
-- Name: imports_productsourcerow_external_file_id_84faa13b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_productsourcerow_external_file_id_84faa13b ON public.imports_productsourcerow USING btree (external_file_id);


--
-- Name: imports_productsourcerow_product_code_normalized_05de07f6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_productsourcerow_product_code_normalized_05de07f6 ON public.imports_productsourcerow USING btree (product_code_normalized);


--
-- Name: imports_productsourcerow_product_code_normalized_05de07f6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_productsourcerow_product_code_normalized_05de07f6_like ON public.imports_productsourcerow USING btree (product_code_normalized varchar_pattern_ops);


--
-- Name: imports_stocksourcerow_external_file_id_e84d59dc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_stocksourcerow_external_file_id_e84d59dc ON public.imports_stocksourcerow USING btree (external_file_id);


--
-- Name: imports_stocksourcerow_product_code_normalized_58851494; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_stocksourcerow_product_code_normalized_58851494 ON public.imports_stocksourcerow USING btree (product_code_normalized);


--
-- Name: imports_stocksourcerow_product_code_normalized_58851494_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX imports_stocksourcerow_product_code_normalized_58851494_like ON public.imports_stocksourcerow USING btree (product_code_normalized varchar_pattern_ops);


--
-- Name: locations_fromaddress_client_id_34578f1a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_fromaddress_client_id_34578f1a ON public.locations_fromaddress USING btree (client_id);


--
-- Name: locations_s_state_d9cf1b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_s_state_d9cf1b_idx ON public.locations_suburb USING btree (state, postcode);


--
-- Name: locations_s_suburb__b8876b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_s_suburb__b8876b_idx ON public.locations_suburb USING btree (suburb_name, state);


--
-- Name: locations_suburb_normalized_key_10915a0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_suburb_normalized_key_10915a0e ON public.locations_suburb USING btree (normalized_key);


--
-- Name: locations_suburb_normalized_key_10915a0e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_suburb_normalized_key_10915a0e_like ON public.locations_suburb USING btree (normalized_key varchar_pattern_ops);


--
-- Name: products_pr_client__8a8842_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_pr_client__8a8842_idx ON public.products_product USING btree (client_id, name);


--
-- Name: products_pr_client__abaa70_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_pr_client__abaa70_idx ON public.products_product USING btree (client_id, sku);


--
-- Name: products_product_client_id_92d0d89f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_client_id_92d0d89f ON public.products_product USING btree (client_id);


--
-- Name: products_productkitcomponent_client_id_1b36b1c8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_productkitcomponent_client_id_1b36b1c8 ON public.products_productkitcomponent USING btree (client_id);


--
-- Name: rates_carriertailgatecharge_carrier_id_1ffee9a7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_carriertailgatecharge_carrier_id_1ffee9a7 ON public.rates_carriertailgatecharge USING btree (carrier_id);


--
-- Name: rates_carriertailgatecharge_client_id_24865f74; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_carriertailgatecharge_client_id_24865f74 ON public.rates_carriertailgatecharge USING btree (client_id);


--
-- Name: rates_freig_client__59464e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freig_client__59464e_idx ON public.rates_freightzone USING btree (client_id, postcode);


--
-- Name: rates_freig_client__a858ee_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freig_client__a858ee_idx ON public.rates_freightrate USING btree (client_id, lookup_key);


--
-- Name: rates_freig_client__a9de05_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freig_client__a9de05_idx ON public.rates_freightzone USING btree (client_id, suburb, state);


--
-- Name: rates_freightrate_carrier_service_id_d660757b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightrate_carrier_service_id_d660757b ON public.rates_freightrate USING btree (carrier_service_id);


--
-- Name: rates_freightrate_client_id_3a7c5752; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightrate_client_id_3a7c5752 ON public.rates_freightrate USING btree (client_id);


--
-- Name: rates_freightrate_lookup_key_252697bb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightrate_lookup_key_252697bb ON public.rates_freightrate USING btree (lookup_key);


--
-- Name: rates_freightrate_lookup_key_252697bb_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightrate_lookup_key_252697bb_like ON public.rates_freightrate USING btree (lookup_key varchar_pattern_ops);


--
-- Name: rates_freightzone_carrier_service_id_e516f111; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightzone_carrier_service_id_e516f111 ON public.rates_freightzone USING btree (carrier_service_id);


--
-- Name: rates_freightzone_client_id_636a61e5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightzone_client_id_636a61e5 ON public.rates_freightzone USING btree (client_id);


--
-- Name: rates_freightzone_lookup_key_postcode_16b1808b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightzone_lookup_key_postcode_16b1808b ON public.rates_freightzone USING btree (lookup_key_postcode);


--
-- Name: rates_freightzone_lookup_key_postcode_16b1808b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightzone_lookup_key_postcode_16b1808b_like ON public.rates_freightzone USING btree (lookup_key_postcode varchar_pattern_ops);


--
-- Name: rates_freightzone_lookup_key_suburb_3b4a43dc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightzone_lookup_key_suburb_3b4a43dc ON public.rates_freightzone USING btree (lookup_key_suburb);


--
-- Name: rates_freightzone_lookup_key_suburb_3b4a43dc_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rates_freightzone_lookup_key_suburb_3b4a43dc_like ON public.rates_freightzone USING btree (lookup_key_suburb varchar_pattern_ops);


--
-- Name: saved_est_client_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX saved_est_client_created ON public.saved_estimates_savedestimate USING btree (client_id, created_at DESC);


--
-- Name: saved_est_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX saved_est_user_created ON public.saved_estimates_savedestimate USING btree (created_by_id, created_at DESC);


--
-- Name: saved_estimates_savedestimate_client_id_de26b4c3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX saved_estimates_savedestimate_client_id_de26b4c3 ON public.saved_estimates_savedestimate USING btree (client_id);


--
-- Name: saved_estimates_savedestimate_created_by_id_8325c4a8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX saved_estimates_savedestimate_created_by_id_8325c4a8 ON public.saved_estimates_savedestimate USING btree (created_by_id);


--
-- Name: saved_estimates_savedestimate_reference_6cec9eb7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX saved_estimates_savedestimate_reference_6cec9eb7_like ON public.saved_estimates_savedestimate USING btree (reference varchar_pattern_ops);


--
-- Name: audit_auditevent audit_auditevent_actor_id_270bb4b7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_auditevent
    ADD CONSTRAINT audit_auditevent_actor_id_270bb4b7_fk_auth_user_id FOREIGN KEY (actor_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_auditevent audit_auditevent_client_id_b7cf9ec4_fk_clients_client_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_auditevent
    ADD CONSTRAINT audit_auditevent_client_id_b7cf9ec4_fk_clients_client_id FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_auditevent audit_auditevent_external_file_id_0ef52357_fk_imports_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_auditevent
    ADD CONSTRAINT audit_auditevent_external_file_id_0ef52357_fk_imports_e FOREIGN KEY (external_file_id) REFERENCES public.imports_externaldatafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_gateway_calculatoruserprofile_allowed_clients authentication_gatew_calculatoruserprofil_94d347db_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile_allowed_clients
    ADD CONSTRAINT authentication_gatew_calculatoruserprofil_94d347db_fk_authentic FOREIGN KEY (calculatoruserprofile_id) REFERENCES public.authentication_gateway_calculatoruserprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_gateway_calculatoruserprofile_allowed_clients authentication_gatew_client_id_1210bcb2_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile_allowed_clients
    ADD CONSTRAINT authentication_gatew_client_id_1210bcb2_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_gateway_calculatoruserprofile authentication_gatew_client_id_c76711e3_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile
    ADD CONSTRAINT authentication_gatew_client_id_c76711e3_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_gateway_calculatoruserprofile authentication_gatew_user_id_eadcebf4_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_gateway_calculatoruserprofile
    ADD CONSTRAINT authentication_gatew_user_id_eadcebf4_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carriers_carrierservice carriers_carrierserv_carrier_id_4b678580_fk_carriers_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_carrierservice
    ADD CONSTRAINT carriers_carrierserv_carrier_id_4b678580_fk_carriers_ FOREIGN KEY (carrier_id) REFERENCES public.carriers_carrier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carriers_clientcarrierconfig carriers_clientcarri_carrier_service_id_5f7bde01_fk_carriers_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_clientcarrierconfig
    ADD CONSTRAINT carriers_clientcarri_carrier_service_id_5f7bde01_fk_carriers_ FOREIGN KEY (carrier_service_id) REFERENCES public.carriers_carrierservice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carriers_clientcarrierconfig carriers_clientcarri_client_id_4355b5f2_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_clientcarrierconfig
    ADD CONSTRAINT carriers_clientcarri_client_id_4355b5f2_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carriers_clientcarrierconfig carriers_clientcarri_fuel_data_file_id_a037f4b0_fk_imports_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carriers_clientcarrierconfig
    ADD CONSTRAINT carriers_clientcarri_fuel_data_file_id_a037f4b0_fk_imports_e FOREIGN KEY (fuel_data_file_id) REFERENCES public.imports_externaldatafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clients_freightcalculator clients_freightcalcu_client_id_36cb7f7e_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients_freightcalculator
    ADD CONSTRAINT clients_freightcalcu_client_id_36cb7f7e_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_externaldatafile imports_externaldata_activated_by_id_6efc2ba2_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldata_activated_by_id_6efc2ba2_fk_auth_user FOREIGN KEY (activated_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_externaldatafile imports_externaldata_client_id_ec2c0529_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldata_client_id_ec2c0529_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_externaldatafile imports_externaldata_imported_by_id_d75cf480_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldata_imported_by_id_d75cf480_fk_auth_user FOREIGN KEY (imported_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_externaldatafile imports_externaldata_previous_active_file_a8159ee8_fk_imports_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldata_previous_active_file_a8159ee8_fk_imports_e FOREIGN KEY (previous_active_file_id) REFERENCES public.imports_externaldatafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_externaldatafile imports_externaldata_rolled_back_by_id_af5c253f_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldata_rolled_back_by_id_af5c253f_fk_auth_user FOREIGN KEY (rolled_back_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_externaldatafile imports_externaldata_uploaded_by_id_d42115b5_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldata_uploaded_by_id_d42115b5_fk_auth_user FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_externaldatafile imports_externaldata_validated_by_id_8f30fe70_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_externaldatafile
    ADD CONSTRAINT imports_externaldata_validated_by_id_8f30fe70_fk_auth_user FOREIGN KEY (validated_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_productsourcerow imports_productsourc_external_file_id_84faa13b_fk_imports_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_productsourcerow
    ADD CONSTRAINT imports_productsourc_external_file_id_84faa13b_fk_imports_e FOREIGN KEY (external_file_id) REFERENCES public.imports_externaldatafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: imports_stocksourcerow imports_stocksourcer_external_file_id_e84d59dc_fk_imports_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imports_stocksourcerow
    ADD CONSTRAINT imports_stocksourcer_external_file_id_e84d59dc_fk_imports_e FOREIGN KEY (external_file_id) REFERENCES public.imports_externaldatafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: locations_fromaddress locations_fromaddress_client_id_34578f1a_fk_clients_client_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations_fromaddress
    ADD CONSTRAINT locations_fromaddress_client_id_34578f1a_fk_clients_client_id FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_client_id_92d0d89f_fk_clients_client_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_client_id_92d0d89f_fk_clients_client_id FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productkitcomponent products_productkitc_client_id_1b36b1c8_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_productkitcomponent
    ADD CONSTRAINT products_productkitc_client_id_1b36b1c8_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rates_carriertailgatecharge rates_carriertailgat_carrier_id_1ffee9a7_fk_carriers_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_carriertailgatecharge
    ADD CONSTRAINT rates_carriertailgat_carrier_id_1ffee9a7_fk_carriers_ FOREIGN KEY (carrier_id) REFERENCES public.carriers_carrier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rates_carriertailgatecharge rates_carriertailgat_client_id_24865f74_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_carriertailgatecharge
    ADD CONSTRAINT rates_carriertailgat_client_id_24865f74_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rates_freightrate rates_freightrate_carrier_service_id_d660757b_fk_carriers_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_freightrate
    ADD CONSTRAINT rates_freightrate_carrier_service_id_d660757b_fk_carriers_ FOREIGN KEY (carrier_service_id) REFERENCES public.carriers_carrierservice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rates_freightrate rates_freightrate_client_id_3a7c5752_fk_clients_client_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_freightrate
    ADD CONSTRAINT rates_freightrate_client_id_3a7c5752_fk_clients_client_id FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rates_freightzone rates_freightzone_carrier_service_id_e516f111_fk_carriers_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_freightzone
    ADD CONSTRAINT rates_freightzone_carrier_service_id_e516f111_fk_carriers_ FOREIGN KEY (carrier_service_id) REFERENCES public.carriers_carrierservice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rates_freightzone rates_freightzone_client_id_636a61e5_fk_clients_client_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates_freightzone
    ADD CONSTRAINT rates_freightzone_client_id_636a61e5_fk_clients_client_id FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_estimates_savedestimate saved_estimates_save_client_id_de26b4c3_fk_clients_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_estimates_savedestimate
    ADD CONSTRAINT saved_estimates_save_client_id_de26b4c3_fk_clients_c FOREIGN KEY (client_id) REFERENCES public.clients_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_estimates_savedestimate saved_estimates_save_created_by_id_8325c4a8_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_estimates_savedestimate
    ADD CONSTRAINT saved_estimates_save_created_by_id_8325c4a8_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 65vDab7vxIXxzkBvEifQktDd9Z5mgQBtBFyF0INp3ZlDkOntakOVQPNYF16uVUE
