# Generated by Django 5.1.4 on 2026-09-24 22:46

import apps.clients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['code'], 'verbose_name': 'Calculator Customer', 'verbose_name_plural': 'Calculator Customers'},
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('group', models.CharField(blank=True, max_length=40)),
                ('group1', models.CharField(blank=True, max_length=40)),
                ('group2', models.CharField(blank=True, max_length=40)),
                ('their_code', models.CharField(blank=True, max_length=40)),
                ('wh_pick_code', models.CharField(blank=True, max_length=40)),
                ('acn', models.CharField(blank=True, max_length=40)),
                ('abn', models.CharField(blank=True, max_length=40)),
                ('gst_code', models.CharField(blank=True, max_length=40)),
                ('sett_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paydays_type', models.CharField(blank=True, max_length=40)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('source_user', models.CharField(blank=True, max_length=80)),
                ('is_special', models.BooleanField(default=False)),
                ('source_row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translogic_customer', to='clients.client', verbose_name='Calculator Customer')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to=apps.clients.models.customer_import_upload_to)),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField()),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('special_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='IMPORTED', max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer import',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(
                condition=models.Q(('is_special', False), ('linked_client__isnull', True), _connector='OR'),
                name='clients_special_customer_unlinked',
            ),
        ),
    ]
