# Generated by Django 5.1.4 on 2026-06-04 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('PRODUCTS', 'Products'), ('STOCK', 'Stock'), ('FUEL', 'Fuel'), ('ZONES', 'Zones'), ('RATES', 'Rates'), ('SUBURBS', 'Suburbs'), ('WORKBOOK', 'Full Excel Workbook')], max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('IMPORTED', 'Imported'), ('ERROR', 'Error'), ('ARCHIVED', 'Archived')], default='UPLOADED', max_length=20)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_files', to='clients.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
