# Generated by Django 5.1.4 on 2026-06-04 09:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CarrierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=40)),
                ('service_name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='carriers.carrier')),
            ],
            options={
                'ordering': ['carrier__code', 'service_code'],
                'unique_together': {('carrier', 'service_code')},
            },
        ),
        migrations.CreateModel(
            name='ClientCarrierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(default='STH', max_length=30)),
                ('ratecard', models.CharField(blank=True, max_length=80)),
                ('fuel_levy', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('extra_surcharge', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('uprate', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('cubic_conversion', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('tailgate_enabled', models.BooleanField(default=False)),
                ('hand_unload_enabled', models.BooleanField(default=False)),
                ('subzone_enabled', models.BooleanField(default=False)),
                ('area_enabled', models.BooleanField(default=False)),
                ('overlength_enabled', models.BooleanField(default=False)),
                ('pallet_enabled', models.BooleanField(default=True)),
                ('carton_enabled', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('carrier_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrierservice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_configs', to='clients.client')),
            ],
            options={
                'ordering': ['client__code', 'carrier_service__carrier__code'],
                'unique_together': {('client', 'carrier_service')},
            },
        ),
    ]
