# Generated by Django 5.1.4 on 2026-06-04 09:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('length_m', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('width_m', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('height_m', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('weight_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('cubic_m3', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('freight_type', models.CharField(choices=[('P', 'Pallet'), ('C', 'Case/Carton')], default='P', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'sku'], name='products_pr_client__abaa70_idx'), models.Index(fields=['client', 'name'], name='products_pr_client__8a8842_idx')],
                'unique_together': {('client', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductKitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_sku', models.CharField(max_length=80)),
                ('component_sku', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'unique_together': {('client', 'parent_sku', 'component_sku')},
            },
        ),
    ]
