# Generated by Django 5.1.4 on 2026-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_client__abaa70_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('client', 'customer_code', 'sku')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['client', 'customer_code', 'sku'], name='products_pr_client__3d6b16_idx'),
        ),
    ]
